server:
    port: 8761

management:
  security:
    enabled: false

eureka:
    instance:
        hostname: eureka-server
        preferIpAddress: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    server:
      enable-self-preservation: false