server:
  port: 8080

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

spring:
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/

logging:
  level:
    de:
     codecentric: DEBUG
